site_name: OpenAI Sandbox
site_description: Learn Open AI By Experimenting
site_author: Nitya Narasimhan
site_url: https://ai-for-autodidacts.github.io/openai

# Repository
repo_name: ai-for-autodidacts/openai
repo_url: https://github.com/ai-for-autodidacts/openai

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.select
    - content.tooltips
    - announce.dismiss
  language: en
  
  palette:
    - scheme: default
      primary: custom
      accent: custom
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Inter
    code: JetBrains Mono

  icon:
    repo: fontawesome/brands/github

plugins:
  - search

extra:
  generator: false

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

copyright: Copyright &copy; 2025 Nitya Narasimhan

nav:
  - Home: index.md
  - Quickstart:
    - Overview: 1-quickstart/index.md
  - Inference:
    - Overview: 2-model-inference/index.md
  - Customization:
    - Overview: 3-model-customization/index.md
  - Evaluation:
    - Overview: 4-model-evaluation/index.md
  - Agentic AI:
    - Overview: 5-agentic-ai/index.md
  - Advanced Topics:
    - Overview: 6-advanced-topics/index.md
